"""Kepler: SIMBAD object-type vocabulary.

SIMBAD tags every object with a machine ``otype`` code — ``GlCl``, ``EB*``,
``gammaBurst`` — and Kepler surfaces those to users as prose. This is the
mapping, and it is a plain lookup table with no behaviour attached; the resolver
that consumes it is ``query/simbad.py``.

The table is reproduced exactly as Kepler's upstream carried it, empty strings
and all. Three points worth knowing before editing:

* Two entries map to the empty string (``Possible_As*``, ``Unknown``). Callers
  must treat "present but empty" as "no label", not as a missing key.
* The vocabulary is SIMBAD's, not Kepler's. Codes are added and retired
  upstream; an unrecognized code means SIMBAD moved, and the resolver falls
  back to the raw code rather than failing.
* ``Inexistent`` is a real SIMBAD code meaning "not an object (error, artefact)".
  It is not a placeholder and should not be pruned.

EXTRACTED FROM: skynet/apps/public-api/public_api/services/target_search.py
(lines 27-234 of 394), verbatim.
"""

__all__ = ["SIMBAD_OBJECT_TYPES"]


SIMBAD_OBJECT_TYPES = {
    "Transient": "transient event",
    "Radio": "Radio-source",
    "Radio(m)": "metric Radio-source",
    "Radio(cm)": "centimetric Radio-source",
    "Radio(mm)": "millimetric Radio-source",
    "Radio(sub-mm)": "sub-millimetric source",
    "HI": "HI (21cm) source",
    "radioBurst": "radio Burst",
    "Maser": "Maser",
    "IR": "Infra-Red source",
    "FIR": "Far-Infrared source",
    "MIR": "Mid-Infrared source",
    "NIR": "Near-Infrared source",
    "Blue": "Blue object",
    "UV": "UV-emission source",
    "X": "X-ray source",
    "ULX?": "Ultra-luminous X-ray candidate",
    "ULX": "Ultra-luminous X-ray source",
    "gamma": "gamma-ray source",
    "gammaBurst": "gamma-ray Burst",
    "Inexistent": "Not an object (error, artefact, ...)",
    "Gravitation": "Gravitational Source",
    "LensingEv": "(Micro)Lensing Event",
    "Candidate_LensSystem": "Possible gravitational lens System",
    "Candidate_Lens": "Possible gravitational lens",
    "Possible_lensImage": "Possible gravitationally lensed image",
    "GravLens": "Gravitational Lens",
    "GravLensSystem": "Gravitational Lens System (lens+images)",
    "GravWaveEvent": "Gravitational Wave Event",
    "Candidates": "Candidate objects",
    "Possible_G": "Possible Galaxy",
    "Possible_SClG": "Possible Supercluster of Galaxies",
    "Possible_ClG": "Possible Cluster of Galaxies",
    "Possible_GrG": "Possible Group of Galaxies",
    "Possible_As*": "",
    "Candidate_**": "Physical Binary Candidate",
    "Candidate_EB*": "Eclipsing Binary Candidate",
    "Candidate_Symb*": "Symbiotic Star Candidate",
    "Candidate_CV*": "Cataclysmic Binary Candidate",
    "Candidate_Nova": "Nova Candidate",
    "Candidate_XB*": "X-ray binary Candidate",
    "Candidate_LMXB": "Low-Mass X-ray binary Candidate",
    "Candidate_HMXB": "High-Mass X-ray binary Candidate",
    "Candidate_Pec*": "Possible Peculiar Star",
    "Candidate_YSO": "Young Stellar Object Candidate",
    "Candidate_TTau*": "T Tau star Candidate",
    "Candidate_C*": "Possible Carbon Star",
    "Candidate_S*": "Possible S Star",
    "Candidate_OH": "Possible Star with envelope of OH/IR type",
    "Candidate_WR*": "Possible Wolf-Rayet Star",
    "Candidate_Be*": "Possible Be Star",
    "Candidate_Ae*": "Possible Herbig Ae/Be Star",
    "Candidate_HB*": "Possible Horizontal Branch Star",
    "Candidate_RRLyr": "Possible Star of RR Lyr type",
    "Candidate_Cepheid": "Possible Cepheid",
    "Candidate_PulsV*WVir": "Possible Variable Star of W Vir type",
    "Candidate_RGB*": "Possible Red Giant Branch star",
    "Candidate_SG*": "Possible Supergiant star",
    "Candidate_RSG*": "Possible Red supergiant star",
    "Candidate_YSG*": "Possible Yellow supergiant star",
    "Candidate_BSG*": "Possible Blue supergiant star",
    "Candidate_AGB*": "Asymptotic Giant Branch Star candidate",
    "Candidate_LP*": "Long Period Variable candidate",
    "Candidate_Mi*": "Mira candidate",
    "Candidate_post-AGB*": "Post-AGB Star Candidate",
    "Candidate_BSS": "Candidate blue Straggler Star",
    "Candidate_Hsd": "Hot subdwarf candidate",
    "Candidate_WD*": "White Dwarf Candidate",
    "Candidate_NS": "Neutron Star Candidate",
    "Candidate_BH": "Black Hole Candidate",
    "Candidate_SN*": "SuperNova Candidate",
    "Candidate_low-mass*": "Low-mass star candidate",
    "Candidate_brownD*": "Brown Dwarf Candidate",
    "multiple_object": "Composite object",
    "Region": "Region defined in the sky",
    "Void": "Underdense region of the Universe",
    "SuperClG": "Supercluster of Galaxies",
    "ClG": "Cluster of Galaxies",
    "GroupG": "Group of Galaxies",
    "Compact_Gr_G": "Compact Group of Galaxies",
    "PairG": "Pair of Galaxies",
    "IG": "Interacting Galaxies",
    "Cl*?": "Possible (open) star cluster",
    "GlCl?": "Possible Globular Cluster",
    "Cl*": "Cluster of Stars",
    "GlCl": "Globular Cluster",
    "OpCl": "Open (galactic) Cluster",
    "Assoc*": "Association of Stars",
    "Stream*": "Stellar Stream",
    "MouvGroup": "Moving Group",
    "**": "Double or multiple star",
    "EB*": "Eclipsing binary",
    "SB*": "Spectroscopic binary",
    "EllipVar": "Ellipsoidal variable Star",
    "Symbiotic*": "Symbiotic Star",
    "CataclyV*": "Cataclysmic Variable Star",
    "Nova": "Nova",
    "XB": "X-ray Binary",
    "LMXB": "Low Mass X-ray Binary",
    "HMXB": "High Mass X-ray Binary",
    "ISM": "Interstellar matter",
    "PartofCloud": "Part of Cloud",
    "PN?": "Possible Planetary Nebula",
    "ComGlob": "Cometary Globule",
    "Bubble": "Bubble",
    "EmObj": "Emission Object",
    "Cloud": "Cloud",
    "GalNeb": "Galactic Nebula",
    "DkNeb": "Dark Cloud (nebula)",
    "RfNeb": "Reflection Nebula",
    "MolCld": "Molecular Cloud",
    "Globule": "Globule (low-mass dark cloud)",
    "denseCore": "Dense core",
    "SFregion": "Star forming region",
    "HVCld": "High-velocity Cloud",
    "HII": "HII (ionized) region",
    "PN": "Planetary Nebula",
    "HIshell": "HI shell",
    "SNR?": "SuperNova Remnant Candidate",
    "SNR": "SuperNova Remnant",
    "outflow?": "Outflow candidate",
    "Outflow": "Outflow",
    "HH": "Herbig-Haro Object",
    "Star": "Star",
    "V*?": "Star suspected of Variability",
    "Pec*": "Peculiar Star",
    "HB*": "Horizontal Branch Star",
    "YSO": "Young Stellar Object",
    "Ae*": "Herbig Ae/Be star",
    "Em*": "Emission-line Star",
    "Be*": "Be Star",
    "BlueStraggler": "Blue Straggler Star",
    "RGB*": "Red Giant Branch star",
    "AGB*": "Asymptotic Giant Branch Star (He-burning)",
    "C*": "Carbon Star",
    "S*": "S Star",
    "SG*": "Evolved supergiant star",
    "RedSG*": "Red supergiant star",
    "YellowSG*": "Yellow supergiant star",
    "BlueSG*": "Blue supergiant star",
    "HotSubdwarf": "Hot subdwarf",
    "post-AGB*": "Post-AGB Star (proto-PN)",
    "WD*": "White Dwarf",
    "low-mass*": "Low-mass star (M<1solMass)",
    "brownD*": "Brown Dwarf (M<0.08solMass)",
    "Neutron*": "Confirmed Neutron Star",
    "OH/IR": "OH/IR star",
    "TTau*": "T Tau-type Star",
    "WR*": "Wolf-Rayet Star",
    "PM*": "High proper-motion Star",
    "HV*": "High-velocity Star",
    "V*": "Variable Star",
    "Irregular_V*": "Variable Star of irregular type",
    "Orion_V*": "Variable Star of Orion Type",
    "Eruptive*": "Eruptive variable Star",
    "Erupt*RCrB": "Variable Star of R CrB type",
    "RCrB_Candidate": "Variable Star of R CrB type candiate",
    "RotV*": "Rotationally variable Star",
    "RotV*alf2CVn": "Variable Star of alpha2 CVn type",
    "Pulsar": "Pulsar",
    "BYDra": "Variable of BY Dra type",
    "RSCVn": "Variable of RS CVn type",
    "PulsV*": "Pulsating variable Star",
    "RRLyr": "Variable Star of RR Lyr type",
    "Cepheid": "Cepheid variable Star",
    "PulsV*delSct": "Variable Star of delta Sct type",
    "PulsV*RVTau": "Variable Star of RV Tau type",
    "PulsV*WVir": "Variable Star of W Vir type",
    "PulsV*bCep": "Variable Star of beta Cep type",
    "deltaCep": "Classical Cepheid (delta Cep type)",
    "gammaDor": "Variable Star of gamma Dor type",
    "pulsV*SX": "Variable Star of SX Phe type (subdwarf)",
    "LPV*": "Long-period variable star",
    "Mira": "Variable Star of Mira Cet type",
    "SN": "SuperNova",
    "Sub-stellar": "Sub-stellar object",
    "Planet?": "Extra-solar Planet Candidate",
    "Planet": "Extra-solar Confirmed Planet",
    "Galaxy": "Galaxy",
    "PartofG": "Part of a Galaxy",
    "GinCl": "Galaxy in Cluster of Galaxies",
    "BClG": "Brightest galaxy in a Cluster (BCG)",
    "GinGroup": "Galaxy in Group of Galaxies",
    "GinPair": "Galaxy in Pair of Galaxies",
    "RadioG": "Radio Galaxy",
    "HII_G": "HII Galaxy",
    "LSB_G": "Low Surface Brightness Galaxy",
    "AGN_Candidate": "Possible Active Galaxy Nucleus",
    "QSO_Candidate": "Possible Quasar",
    "Blazar_Candidate": "Possible Blazar",
    "BLLac_Candidate": "Possible BL Lac",
    "EmG": "Emission-line galaxy",
    "StarburstG": "Starburst Galaxy",
    "BlueCompG": "Blue compact Galaxy",
    "LensedImage": "Gravitationally Lensed Image",
    "LensedG": "Gravitationally Lensed Image of a Galaxy",
    "LensedQ": "Gravitationally Lensed Image of a Quasar",
    "AGN": "Active Galaxy Nucleus",
    "LINER": "LINER-type Active Galaxy Nucleus",
    "Seyfert": "Seyfert Galaxy",
    "Seyfert_1": "Seyfert 1 Galaxy",
    "Seyfert_2": "Seyfert 2 Galaxy",
    "Blazar": "Blazar",
    "BLLac": "BL Lac - type object",
    "OVV": "Optically Violently Variable object",
    "QSO": "Quasar",
}
